### ISSUE TITLE
Simple example with ethernet passthrough hangs VM

### ISSUE THREAD

**Issue by adam-yt** [au-ts/libvmm#134]
I am creating a VMM with ethernet passthrough by modifying the simple example for qemu_virt_aarch64, however, the VM hangs when running `udhcpc` or `ip link set eth0 up`. Running `ip addr show` shows the iface `eth0`, but without an IP.

### Steps to recreate
Add ethernet memory region, map and irq to `examples/simple/board/qemu_virt_aarch64/simple.system`:

```
<?xml version="1.0" encoding="UTF-8"?>
<system>
    <memory_region name="guest_ram" size="0x10_000_000" page_size="0x200_000" />
    <memory_region name="ethernet" size="0x1_000" phys_addr="0xa003000" />
    <memory_region name="serial" size="0x1_000" phys_addr="0x9000000" />
    <memory_region name="gic_vcpu" size="0x1_000" phys_addr="0x8040000" />

    <protection_domain name="VMM" priority="254">
        <program_image path="vmm.elf" />
        <map mr="guest_ram" vaddr="0x40000000" perms="rw" setvar_vaddr="guest_ram_vaddr" />
        <virtual_machine name="linux" >
            <vcpu id="0" />
            <map mr="guest_ram" vaddr="0x40000000" perms="rwx" />
            <map mr="ethernet" vaddr="0xa003000" perms="rw" cached="false" />
            <map mr="serial" vaddr="0x9000000" perms="rw" cached="false" />
            <map mr="gic_vcpu" vaddr="0x8010000" perms="rw" cached="false" />
        </virtual_machine>
        <irq irq="33" id="1" /> <!--Serial -->
        <irq irq="79" id="2" trigger="edge" /><!--Ethernet-->
    </protection_domain>
</system>
```

Add this device to `examples/simple/board/qemu_virt_aarch64/overlay.dts`:
```
virtio-net@a003e00 {
		dma-coherent;
		interrupts = <0x00 0x2f 0x01>;
		reg = <0x00 0xa003e00 0x00 0x200>;
		compatible = "virtio,mmio";
};
```

Make the following changes in `examples/simple/vmm.c`:
Register ethernet IRQ in `init` function: 
```
void init(void) {
    LOG_VMM("starting \"%s\"\n", microkit_name);
    ... 
    microkit_irq_ack(SERIAL_IRQ_CH);
    success = virq_register_passthrough(GUEST_VCPU_ID, 79, 2);
    if (!success) {
        LOG_VMM_ERR("Failed to register ethernet IRQ");
    }
    guest_start(GUEST_VCPU_ID, kernel_pc, GUEST_DTB_VADDR, GUEST_INIT_RAM_DISK_VADDR);
}
```
Handle ethernet irq in `notified` function:
```
void notified(microkit_channel ch) {
    switch (ch) {
        case 2: {
            bool success = virq_handle_passthrough(ch);
            if (!success) {
                LOG_VMM_ERR("IRQ %d dropped on vCPU %d\n", 79, GUEST_VCPU_ID);
            }
            break;
        }
        ...
}
```

In  `examples/simple/simple.mk`, supply `qemu` target command with the options `-netdev user,id=mynet0 -device virtio-net-device,netdev=mynet0`.

Build the example according to the readme under simple example. Once the VM has booted, run `udhcpc` or `ip link set eth0 up`, causing the VM to hang.

**Comment by Ivan-Velickovic** [comment]
You are very close, there is one step left:
```diff
-<memory_region name="guest_ram" size="0x10_000_000" page_size="0x200_000" />
+<memory_region name="guest_ram" size="0x10_000_000" page_size="0x200_000" phys_addr="0x40000000" />
```

Ethernet devices transfer via DMA, which means that when Linux allocates a guest physical address from RAM for DMA (in this case, somewhere around `0x40000000` since that's where RAM starts), it passes it to the device. But, the device does not work in guest physical memory, it works in *real* physical memory, which means that it will try to access `0x40000000` even though the physical address for guest RAM is somewhere else.

Hence, the hanging.

After adding this I was able to get the following:
```
# ifconfig eth0 up
# udhcpc
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: broadcasting select for 10.0.2.15, server 10.0.2.2
udhcpc: lease of 10.0.2.15 obtained from 10.0.2.2, lease time 86400
deleting routers
adding dns 10.0.2.3
# ping google.com
PING google.com (142.251.221.78): 56 data bytes
64 bytes from 142.251.221.78: seq=0 ttl=255 time=40.012 ms
64 bytes from 142.251.221.78: seq=1 ttl=255 time=35.868 ms
```

There is a section on pass-through devices in the manual that talks about this:
https://github.com/au-ts/libvmm/blob/main/docs/MANUAL.md#passthrough

It is unfortunately a fairly manual and finicky process right now.

Please let us know if we can improve the documentation in any way and let me know if this fixes your issue.

**Comment by Ivan-Velickovic** [comment]
I should add, thank you for writing up the issue nicely. It made it much easier to reproduce myself.

**Comment by adam-yt** [comment]
Thank you for the quick response! Good catch. I added the phys_addr and everything works correctly now
