### ISSUE TITLE
make: *** No rule to make target ...

### ISSUE THREAD

**Issue by hugusmaximus** [au-ts/libvmm#33]
Just trying to follow instructions for building and running libvmm I'm unable to compile the source code. I already downloaded the pre-built sdk and tried the make command:

hugo@anakin:~/libvmm$ make BOARD=qemu_arm_virt MICROKIT_SDK=../microkit-sdk-1.2.6 qemu
make: *** No rule to make target 'qemu'.  Stop.

Don't we need config? Or do I need to launch the command from any other place/environment?

I guess I'm missing something, but reading the instructions I don't guess what... (I'm not a developer so excuse me in advance).

**Comment by Ivan-Velickovic** [comment]
Fixed, it was missing a `cd examples/simple` before the Make command. Hopefully that fixes it!
