### ISSUE TITLE
Get virtIO example working with macOS again

### ISSUE THREAD

**Issue by Ivan-Velickovic** [au-ts/libvmm#73]
The virtIO block part of the example depends on `mkfs.fat` which does not exist on macOS or on Homebrew to my knowledge.

We've been able to get around this by using Nix since it does provide it for macOS, but we would prefer not to force Nix onto people who want to build the example.

Right now the CI for macOS does not test the virtIO example, we should fix this as well.

**Comment by alexandermbrown** [comment]
We can use https://formulae.brew.sh/formula/dosfstools for `mkfs.fat` but we still need to workaround the differences between macOS and Linux's `fdisk`
