### ISSUE TITLE
Inconsistent method to specify `NUM_CLIENTS` in config files

### ISSUE THREAD

**Issue by alexandermbrown** [au-ts/libvmm#82]
Currently sDDF defines `*_NUM_CLIENTS` in the Makefile e.g., https://github.com/au-ts/sddf/blob/main/examples/echo_server/echo.mk#L21.

However, in this repository, we put this in the `*_config.h` header file, e.g., https://github.com/au-ts/libvmm/blob/main/examples/virtio/include/blk_config.h#L6 and https://github.com/au-ts/libvmm/blob/main/examples/virtio/include/serial_config.h#L9. We should decide which of these is better then update the build system / config files appropriately.

We cannot use both methods as the Makefile snippets expect these to be defined.

**Comment by Ivan-Velickovic** [comment]
It makes more sense to do it in the config header. Can you please make a PR to fix it in sDDF?
